name: Create Encrypted Properties File

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-properties-file:
    runs-on: ubuntu-latest
    environment: Dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install OpenSSL
        run: sudo apt-get install -y openssl

      - name: Encrypt DB_SECRET
        id: encrypt_secret
        run: |
          echo -n "${{ secrets.DB_SECRET }}" | openssl enc -aes-256-cbc -a -salt -pass pass:${{ secrets.ENV_SECRET_KEY }} -out encrypted_secret.txt
          ENCRYPTED_SECRET=$(cat encrypted_secret.txt)
          echo "::set-output name=encrypted_secret::$ENCRYPTED_SECRET"

      - name: Create properties file
        run: |
          echo "DB_HOST=${{ vars.DB_HOST }}" >> dev.properties
          echo "DB_PORT=${{ vars.DB_PORT }}" >> dev.properties
          echo "DB_USER=${{ vars.DB_USER }}" >> dev.properties
          echo "DB_PASS=${{ steps.encrypt_secret.outputs.encrypted_secret }}" >> dev.properties

      - name: Upload properties file
        uses: actions/upload-artifact@v3
        with:
          name: dev-properties
          path: dev.properties
